# Generated by Django 2.2.16 on 2022-11-06 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(null=True)),
                ('in_use_indicator', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ValueName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DictConfigValueName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_model.DictConfig')),
                ('value_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_model.ValueName')),
            ],
        ),
        migrations.AddField(
            model_name='dictconfig',
            name='value_names',
            field=models.ManyToManyField(through='config_model.DictConfigValueName', to='config_model.ValueName'),
        ),
    ]
